#!/usr/bin/env python3
"""
fix-api-toc.py
Strips the 'Plugins.Saneject.' prefix from namespace names
in api/toc.yml and nests namespaces hierarchically by dot-segment.

Run after `docfx metadata`:
    python python/prebuild.py
"""
from __future__ import annotations

import re
from pathlib import Path


PREFIX = "Plugins.Saneject."
DOCS_ROOT = Path(__file__).resolve().parent.parent.parent
TOC_PATH = DOCS_ROOT / "api" / "toc.yml"


NS_PAT = re.compile(
    r'^- uid: (.+)\n  name: (.+)\n  type: Namespace\n((?:  .+\n)*)',
    re.MULTILINE,
)
ITEM_PAT = re.compile(
    r'  - uid: (.+)\n    name: (.+)\n    type: (.+)'
)


def parse(content):
    namespaces = []
    for match in NS_PAT.finditer(content):
        uid, name, body = match.group(1), match.group(2), match.group(3)
        classes = [
            {"uid": item_match.group(1), "name": item_match.group(2), "type": item_match.group(3)}
            for item_match in ITEM_PAT.finditer(body)
        ]
        namespaces.append({"uid": uid, "name": name, "classes": classes})
    return namespaces


def build_tree(namespaces):
    root = {}
    for namespace in namespaces:
        short = (
            namespace["name"][len(PREFIX):]
            if namespace["name"].startswith(PREFIX)
            else namespace["name"]
        )
        parts = short.split(".")
        node = root
        for part in parts[:-1]:
            node.setdefault(part, {"uid": None, "classes": [], "children": {}})
            node = node[part]["children"]
        node.setdefault(parts[-1], {"uid": None, "classes": [], "children": {}})
        node[parts[-1]]["uid"] = namespace["uid"]
        node[parts[-1]]["classes"] = namespace["classes"]
    return root


def emit(tree, level=1):
    out = []
    padding = "  " * level
    for segment in sorted(tree):
        node = tree[segment]
        out.append(f"{padding}- name: {segment}")
        if node["uid"]:
            out.append(f"{padding}  uid: {node['uid']}")
            out.append(f"{padding}  type: Namespace")
        if node["classes"] or node["children"]:
            out.append(f"{padding}  items:")
            for cls in node["classes"]:
                class_padding = "  " * (level + 1)
                out.append(f"{class_padding}- uid: {cls['uid']}")
                out.append(f"{class_padding}  name: {cls['name']}")
                out.append(f"{class_padding}  type: {cls['type']}")
            if node["children"]:
                out.extend(emit(node["children"], level + 1))
    return out


def main():
    content = TOC_PATH.read_text(encoding="utf-8")

    member_layout_match = re.search(r'memberLayout:\s*(\S+)', content)
    member_layout = member_layout_match.group(1) if member_layout_match else "SamePage"

    namespaces = parse(content)
    if not namespaces:
        if "items:" in content:
            print(f"No raw namespace blocks found in {TOC_PATH}; TOC already appears processed. Leaving it unchanged.")
            return

        raise RuntimeError(
            f"No namespaces found in {TOC_PATH}. "
            "Run this script against the raw DocFX metadata TOC generated by `docfx metadata`."
        )

    print(f"Found {len(namespaces)} namespaces")

    tree = build_tree(namespaces)
    lines = ["### YamlMime:TableOfContent", "items:"]
    lines.extend(emit(tree))
    lines.append(f"memberLayout: {member_layout}")

    TOC_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Rewrote {TOC_PATH}")


if __name__ == "__main__":
    main()
